### ISSUE TITLE
中央仓库的api方法对比最新代码有缺失，请将最新代码更新到maven中央仓库

### ISSUE THREAD

**Issue by SeptemberSett** [JX3API/jx3api-java#1]
至少图片服务的接口都是没有的，还请更新最新代码到中央仓库；
<img width="925" alt="屏幕截图 2024-08-18 093624" src="https://github.com/user-attachments/assets/6fea495c-5046-4500-b73c-1913434e104d">
<img width="925" alt="屏幕截图 2024-08-18 093711" src="https://github.com/user-attachments/assets/518a5a20-ad10-4b65-afbc-86d670ac19c6">

**Comment by grafiechen** [comment]
后续不会再提供图片接口了，这一部分代码后续也会被删除。
最新分支在future，已完成大部分接口测试，后续将会合并到主干分支

**Comment by grafiechen** [comment]
抱歉，没注意到，刚才不小心把这个issues关闭了。。
